# Generated by Django 3.1.7 on 2021-05-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210513_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='serials',
            name='is_alive',
            field=models.BooleanField(default=False),
        ),
    ]
