# Generated by Django 3.1.7 on 2021-05-12 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210513_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serials',
            name='name',
            field=models.ForeignKey(blank=True, db_column='member_userid', default='null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
