# Generated by Django 3.1.7 on 2021-05-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_serials_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serials',
            new_name='IoT',
        ),
    ]
