# Generated by Django 3.1.7 on 2021-05-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20210530_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iot',
            name='location',
            field=models.CharField(default='null', max_length=255, null=True),
        ),
    ]
